# Generated by Django 4.2.18 on 2025-01-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abilities', models.JSONField(default=list)),
                ('types', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
            ],
        ),
    ]
